### PR TITLE
fix wifi-update blobs/ remove unusued service see https://github.com/…

### PR DESCRIPTION
**Pull request by pocarropa**
…LineageOS/android_device_xiaomi_msm8996-common/commit/a67d9f87a6d914f9d2e18af780da53270d87de5c

### CODE REVIEW

**Comment by thune-xiaobai** [comment]
where are those blobs from?

**Comment by ardadem** [comment]
Working everything. Im using now.

**Comment by pocarropa** [comment]
@xiaobai , extracted from your last published rom.

**Comment by xiaobai** [comment]
I think you meant @thune-xiaobai, I definitely have nothing to do with this project. :D

**Comment by pocarropa** [comment]
Ignored commit--> closed

**Pull request closed without merging**
