### PR TITLE
fix build errors

### PR DESCRIPTION
**Pull request by pocarropa**

### CODE REVIEW

**Comment by ardadem** [comment]
Thank you! Fixed my build problems.

**Comment by pocarropa** [comment]
Wellcome ;).

Please @ardadem , report if after build your wifi is working fine, mine is broken.

**Comment by thune-xiaobai** [comment]
@pocarropa make sure zImage and kernel modules from same place

**Comment by ardadem** [comment]
@pocarropa i tried it now. wifi not working :\

**Comment by pocarropa** [comment]
Thanks @thune-xiaobai , fixed by matching kernel and modules and firmware images as you said. @ardadem , check vendor changes on my github.

**Comment by ardadem** [comment]
@thune-xiaobai i tried but device doesn't boot.

**Comment by pocarropa** [comment]
Check both device and vendor changes

**Comment by ardadem** [comment]
i just saw it. im compiling now.

**Comment by ardadem** [comment]
Wifi and wifi tethering working excellent! Thanks again :)

**Pull request merged**
